### ISSUE TITLE
Cassandra failure with more than one Cassandra node

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/clearwater-cassandra#117]
If I spin up Clearwater in containers under Kubernetes, it does not work if
there are multiple Cassandra nodes. This reproduces consistently, with
seemingly certain shards unable to be provisioned. With a single Cassandra
node, it does work consistently.

### Symptoms
 
Here are the symptoms.
 
    root@homestead-4071849772-ca4iy:/usr/share/clearwater/bin# ./create_user 4157700001..4157701000 example.com flibbleflobble 
    ERROR: Failed to retrieve private IDs for public ID sip:4157700004@example.com - HTTP status code 404 
    ERROR: Failed to retrieve iFC for public ID sip:4157700004@example.com - HTTP status code 404 
    ERROR: Failed to find any information for public ID sip:4157700004@example.com. 
    root@homestead-4071849772-ca4iy:/usr/share/clearwater/bin# ./create_user 4157700001..4157701000 example.com flibbleflobble 
    ERROR: Private ID 4157700001@example.com already exists - not creating 
    ERROR: Private ID 4157700002@example.com already exists - not creating 
    ERROR: Private ID 4157700003@example.com already exists - not creating 
    ERROR: Private ID 4157700004@example.com already exists - not creating 
    ERROR: Failed to retrieve private IDs for public ID sip:4157700004@example.com - HTTP status code 404 
    ERROR: Failed to retrieve iFC for public ID sip:4157700004@example.com - HTTP status code 404 
    ERROR: Failed to find any information for public ID sip:4157700004@example.com.

Since repeated attempts fail on the same email address, my guess is that one
shard (if that is the right term) in the cluster is broken. I do seem to have
three functional nodes though.
 
    root@cassandra-3877601991-15zll:/# nodetool status 
    Datacenter: site1 
    ================= 
    Status=Up/Down 
    |/ State=Normal/Leaving/Joining/Moving 
    --  Address     Load       Tokens  Owns (effective)  Host ID                               Rack 
    UN  10.19.0.78  289.1 KB   256     66.7%             bae5bc6c-9745-4a86-a5e9-5e3d51bcb2f7  RAC1 
    UN  10.19.2.89  267.85 KB  256     66.3%             a46cc73c-4577-4262-9a90-6d72b3109a2f  RAC1 
    UN  10.19.3.53  287.38 KB  256     67.0%             c6fd74c4-b797-4a29-b359-b6551eac29f9  RAC1

Sure enough, one of the Cassandra nodes appears to have some odd logs. I saw
this once before, reinstalled and it went away, but I'm now concerned that it's
happening consistently.
 
    plw@PC4003:~/work/architecture/microservices/demo$ kubectl exec cassandra-3877601991-qabv4 -- tail -20 /var/log/cassandra/system.log   
           at org.apache.cassandra.db.Mutation$MutationSerializer.deserializeOneCf(Mutation.java:322) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.db.Mutation$MutationSerializer.deserialize(Mutation.java:302) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.db.Mutation$MutationSerializer.deserialize(Mutation.java:330) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.db.Mutation$MutationSerializer.deserialize(Mutation.java:272) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.net.MessageIn.read(MessageIn.java:99) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.net.IncomingTcpConnection.receiveMessage(IncomingTcpConnection.java:195) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.net.IncomingTcpConnection.receiveMessages(IncomingTcpConnection.java:172) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.net.IncomingTcpConnection.run(IncomingTcpConnection.java:88) ~[apache-cassandra-2.1.15.jar:2.1.15]
    WARN  [MessagingService-Incoming-/10.19.0.78] 2016-12-06 09:28:36,277 IncomingTcpConnection.java:97 - UnknownColumnFamilyException reading from socket; closing 
    org.apache.cassandra.db.UnknownColumnFamilyException: Couldn't find cfId=205243d0-bb0d-11e6-8fc5-e9b99718e783 
           at org.apache.cassandra.db.ColumnFamilySerializer.deserializeCfId(ColumnFamilySerializer.java:164) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.db.ColumnFamilySerializer.deserialize(ColumnFamilySerializer.java:97) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.db.Mutation$MutationSerializer.deserializeOneCf(Mutation.java:322) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.db.Mutation$MutationSerializer.deserialize(Mutation.java:302) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.db.Mutation$MutationSerializer.deserialize(Mutation.java:330) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.db.Mutation$MutationSerializer.deserialize(Mutation.java:272) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.net.MessageIn.read(MessageIn.java:99) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.net.IncomingTcpConnection.receiveMessage(IncomingTcpConnection.java:195) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.net.IncomingTcpConnection.receiveMessages(IncomingTcpConnection.java:172) ~[apache-cassandra-2.1.15.jar:2.1.15] 
           at org.apache.cassandra.net.IncomingTcpConnection.run(IncomingTcpConnection.java:88) ~[apache-cassandra-2.1.15.jar:2.1.15]

More information:

- It fails on subscribers 4, 7, 13, 27, 31, 35, 37, 39, 43, 52, ... (I stopped at that point)

- nodetool reports nothing unusual

        plw@PC4003:~$ kubectl exec cassandra-3877601991-15zll nodetool describecluster 
        Cluster Information: 
               Name: Test Cluster 
               Snitch: org.apache.cassandra.locator.DynamicEndpointSnitch 
               Partitioner: org.apache.cassandra.dht.Murmur3Partitioner 
               Schema versions: 
                       455f10c0-6668-3473-8920-e9bbc20cfe32: [10.19.0.78, 10.19.2.89, 10.19.3.53] 

        plw@PC4003:~$ kubectl exec cassandra-3877601991-hijek nodetool describecluster
        Cluster Information: 
               Name: Test Cluster 
               Snitch: org.apache.cassandra.locator.DynamicEndpointSnitch 
               Partitioner: org.apache.cassandra.dht.Murmur3Partitioner 
               Schema versions: 
                       455f10c0-6668-3473-8920-e9bbc20cfe32: [10.19.0.78, 10.19.2.89, 10.19.3.53] 

        plw@PC4003:~$ kubectl exec cassandra-3877601991-qabv4 nodetool describecluster
        Cluster Information: 
               Name: Test Cluster 
               Snitch: org.apache.cassandra.locator.DynamicEndpointSnitch 
               Partitioner: org.apache.cassandra.dht.Murmur3Partitioner 
               Schema versions: 
                       455f10c0-6668-3473-8920-e9bbc20cfe32: [10.19.0.78, 10.19.2.89, 10.19.3.53]

- However, `nodetool repair` shows something strange. There are a fair number of lines like this:

 
        [2016-12-06 14:44:10,041] Repair session 721ea7c0-bbc2-11e6-8b09-f96914763b9e for range (-4945463583888754662,-4931800108679376555] failed with error org.apache.cassandra.exceptions.RepairException: [repair #721ea7c0-bbc2-11e6-8b09-f96914763b9e on homestead_provisioning/private, (-4945463583888754662,-4931800108679376555]] Sync failed between /10.19.2.89 and /10.19.3.53

    That shows some kind of issues between the first and third nodes. I have
    live TCP connections from the node where I ran nodetool to both of the
    other nodes, and can create more successfully.
 
- I see an error in the logs on the third node:

        ERROR [STREAM-IN-/10.19.2.89] 2016-12-06 14:52:20,883 StreamSession.java:512 - [Stream #9711c5c0-bbc3-11e6-8b09-f96914763b9e] Streaming error occurred
        java.io.IOException: CF 205243d0-bb0d-11e6-8fc5-e9b99718e783 was dropped during streaming
                at org.apache.cassandra.streaming.compress.CompressedStreamReader.read(CompressedStreamReader.java:77) ~[apache-cassandra-2.1.15.jar:2.1.15]
                at org.apache.cassandra.streaming.messages.IncomingFileMessage$1.deserialize(IncomingFileMessage.java:48) ~[apache-cassandra-2.1.15.jar:2.1.15]
                at org.apache.cassandra.streaming.messages.IncomingFileMessage$1.deserialize(IncomingFileMessage.java:38) ~[apache-cassandra-2.1.15.jar:2.1.15]
                at org.apache.cassandra.streaming.messages.StreamMessage.deserialize(StreamMessage.java:56) ~[apache-cassandra-2.1.15.jar:2.1.15]
                at org.apache.cassandra.streaming.ConnectionHandler$IncomingMessageHandler.run(ConnectionHandler.java:276) ~[apache-cassandra-2.1.15.jar:2.1.15]
                at java.lang.Thread.run(Thread.java:745) [na:1.7.0_121]
        INFO  [STREAM-IN-/10.19.2.89] 2016-12-06 14:52:20,883 StreamResultFuture.java:181 - [Stream #9711c5c0-bbc3-11e6-8b09-f96914763b9e] Session with /10.19.2.89 is complete

- My cassandra ultimately comes from this image: http://repo.cw-ngv.com/stable; version of Cassandra is shown as follows.

        INFO  [main] 2016-12-05 17:05:37,176 StorageService.java:622 - Cassandra version: 2.1.15
        INFO  [main] 2016-12-05 17:05:37,176 StorageService.java:623 - Thrift API version: 19.39.0
        INFO  [main] 2016-12-05 17:05:37,179 StorageService.java:624 - CQL supported versions: 2.0.0,3.2.1 (default: 3.2.1)

### Configuration

Here is my cassandra shared config

    plw@PC4003:~/Dropbox/transfer$ kubectl exec homer-3011599582-5s9lr cat /etc/clearwater/shared_config 
    # Deployment definitions 
    home_domain=plw.svc.cluster.local 
    sprout_hostname=sprout.plw.svc.cluster.local 
    hs_hostname=hs.plw.svc.cluster.local:8888 
    hs_provisioning_hostname=hs.plw.svc.cluster.local:8889 
    xdms_hostname=homer.plw.svc.cluster.local:7888
    ralf_hostname=ralf.plw.svc.cluster.local:10888
    chronos_hostname=chronos.plw.svc.cluster.local
    cassandra_hostname=cassandra.plw.svc.cluster.local

    # Email server configuration 
    smtp_smarthost=127.0.0.1
    smtp_username=username 
    smtp_password=password 
    email_recovery_sender=clearwater@plw.svc.cluster.local 

    # I-CSCF/S-CSCF configuration 
    upstream_hostname=sprout.plw.svc.cluster.local 

    # Keys 
    signup_key=secret 
    turn_workaround=secret 
    ellis_api_key=secret 
    ellis_cookie_key=secret 

    reduce_cassandra_mem_usage=Y 
    scscf_uri="sip:sprout.plw.svc.cluster.local:5054;transport=tcp" 
    icscf_uri="sip:sprout.plw.svc.cluster.local:5052;transport=tcp" 
    signaling_dns_server=10.18.0.123 

That `cassandra_hostname` value resolves to all three of the different cluster nodes.

    plw@PC4003:~/Dropbox/transfer$ kubectl exec conntester-479047557-znv0h nslookup cassandra.plw.svc.cluster.local 
    Server:         10.18.0.123 
    Address:        10.18.0.123#53 

    Name:   cassandra.plw.svc.cluster.local 
    Address: 10.19.0.78 
    Name:   cassandra.plw.svc.cluster.local 
    Address: 10.19.2.89 
    Name:   cassandra.plw.svc.cluster.local 
    Address: 10.19.3.53

### Failed workarounds

I tried upgrading from http://repo.cw-ngv.com/stable to
http://repo.cw-ngv.com/latest, but no change.

**Comment by plwhite** [comment]
Cannot assign issue, since I have no permissions, but this has been investigated so far by @eleanor-merry who asked me to raise it.

**Comment by eleanor-merry** [comment]
@plwhite - is this issue resolved? @bossmc thinks it is now?

**Comment by plwhite** [comment]
Think we can mark it resolved in latest release. (I believe I reproed it on the new release, but can no longer do so, so guessing I fat fingered that initial repro somehow.)

**Comment by eleanor-merry** [comment]
Excellent. I'll close this now then, please open it if you see it again.

**Comment by eleanor-merry** [comment]
This was fixed by https://github.com/Metaswitch/homestead/pull/417 and https://github.com/Metaswitch/clearwater-etcd-plugins/pull/19
