### ISSUE TITLE
Monit lost track of Cassandra and created a second process, eventually causing the original process to become unresponsive

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/clearwater-cassandra#126]
#### Symptoms

I started provisioning 100,000 users into homestead-prov at about 9am. When I checked back later, most of them had failed, and it looks like this was because Cassandra was down.

I have two Cassandra processes running, one that's been up since Jan 24th, and one that's being constantly restarted:

```
clearwater@prov-homestead-1:~$ ps aux | grep java
cassand+  8990  1.0 34.9 1737996 1415448 ?     SLl  Jan24  86:36 /usr/lib/jvm/java-7-openjdk-amd64//bin/java -ea -javaagent:/usr/share/cassandra/lib/jamm-0.3.0.jar -XX:+CMSClassUnloadingEnabled -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=42 -Xms1024M -Xmx1024M -Xmn200M -XX:+HeapDumpOnOutOfMemoryError -Xss256k -XX:StringTableSize=1000003 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=1 -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseTLAB -XX:CompileCommandFile=/etc/cassandra/hotspot_compiler -XX:CMSWaitDuration=10000 -XX:+CMSParallelInitialMarkEnabled -XX:+CMSEdenChunksRecordAlways -XX:CMSWaitDuration=10000 -XX:+UseCondCardMark -Dcassandra.jmx.local.port=7199 -XX:+DisableExplicitGC -Dcassandra.ignore_rack=true -Dcassandra.ignore_dc=true -Dlogback.configurationFile=logback.xml -Dcassandra.logdir=/var/log/cassandra -Dcassandra.storagedir= -Dcassandra-pidfile=/var/run/cassandra/cassandra.pid -cp /etc/cassandra:/usr/share/cassandra/lib/ST4-4.0.8.jar:/usr/share/cassandra/lib/airline-0.6.jar:/usr/share/cassandra/lib/antlr-runtime-3.5.2.jar:/usr/share/cassandra/lib/commons-cli-1.1.jar:/usr/share/cassandra/lib/commons-codec-1.2.jar:/usr/share/cassandra/lib/commons-lang3-3.1.jar:/usr/share/cassandra/lib/commons-math3-3.2.jar:/usr/share/cassandra/lib/compress-lzf-0.8.4.jar:/usr/share/cassandra/lib/concurrentlinkedhashmap-lru-1.4.jar:/usr/share/cassandra/lib/disruptor-3.0.1.jar:/usr/share/cassandra/lib/guava-16.0.jar:/usr/share/cassandra/lib/high-scale-lib-1.0.6.jar:/usr/share/cassandra/lib/jackson-core-asl-1.9.2.jar:/usr/share/cassandra/lib/jackson-mapper-asl-1.9.2.jar:/usr/share/cassandra/lib/jamm-0.3.0.jar:/usr/share/cassandra/lib/javax.inject.jar:/usr/share/cassandra/lib/jbcrypt-0.3m.jar:/usr/share/cassandra/lib/jline-1.0.jar:/usr/share/cassandra/lib/jna-4.0.0.jar:/usr/share/cassandra/lib/json-simple-1.1.jar:/usr/share/cassandra/lib/libthrift-0.9.2.jar:/usr/share/cassandra/lib/logback-classic-1.1.2.jar:/usr/share/cassandra/lib/logback-core-1.1.2.jar:/usr/share/cassandra/lib/lz4-1.2.0.jar:/usr/share/cassandra/lib/metrics-core-2.2.0.jar:/usr/share/cassandra/lib/netty-all-4.0.23.Final.jar:/usr/share/cassandra/lib/reporter-config-2.1.0.jar:/usr/share/cassandra/lib/slf4j-api-1.7.2.jar:/usr/share/cassandra/lib/snakeyaml-1.11.jar:/usr/share/cassandra/lib/snappy-java-1.0.5.2.jar:/usr/share/cassandra/lib/stream-2.5.2.jar:/usr/share/cassandra/lib/super-csv-2.1.0.jar:/usr/share/cassandra/lib/thrift-server-0.3.7.jar:/usr/share/cassandra/apache-cassandra-2.1.15.jar:/usr/share/cassandra/apache-cassandra-thrift-2.1.15.jar:/usr/share/cassandra/apache-cassandra.jar:/usr/share/cassandra/cassandra-driver-core-2.0.9.2.jar:/usr/share/cassandra/netty-3.9.0.Final.jar:/usr/share/cassandra/stress.jar: -XX:HeapDumpPath=/var/lib/cassandra/java_1485273696.hprof -XX:ErrorFile=/var/lib/cassandra/hs_err_1485273696.log org.apache.cassandra.service.CassandraDaemon
cassand+ 18387 84.5  3.7 1642104 152452 ?      Sl   13:38   0:01 /usr/lib/jvm/java-7-openjdk-amd64//bin/java -ea -javaagent:/usr/share/cassandra/lib/jamm-0.3.0.jar -XX:+CMSClassUnloadingEnabled -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=42 -Xms1024M -Xmx1024M -Xmn200M -XX:+HeapDumpOnOutOfMemoryError -Xss256k -XX:StringTableSize=1000003 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=1 -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseTLAB -XX:CompileCommandFile=/etc/cassandra/hotspot_compiler -XX:CMSWaitDuration=10000 -XX:+CMSParallelInitialMarkEnabled -XX:+CMSEdenChunksRecordAlways -XX:CMSWaitDuration=10000 -XX:+UseCondCardMark -Dcassandra.jmx.local.port=7199 -XX:+DisableExplicitGC -Dcassandra.ignore_rack=true -Dcassandra.ignore_dc=true -Dlogback.configurationFile=logback.xml -Dcassandra.logdir=/var/log/cassandra -Dcassandra.storagedir= -Dcassandra-pidfile=/var/run/cassandra/cassandra.pid -cp /etc/cassandra:/usr/share/cassandra/lib/ST4-4.0.8.jar:/usr/share/cassandra/lib/airline-0.6.jar:/usr/share/cassandra/lib/antlr-runtime-3.5.2.jar:/usr/share/cassandra/lib/commons-cli-1.1.jar:/usr/share/cassandra/lib/commons-codec-1.2.jar:/usr/share/cassandra/lib/commons-lang3-3.1.jar:/usr/share/cassandra/lib/commons-math3-3.2.jar:/usr/share/cassandra/lib/compress-lzf-0.8.4.jar:/usr/share/cassandra/lib/concurrentlinkedhashmap-lru-1.4.jar:/usr/share/cassandra/lib/disruptor-3.0.1.jar:/usr/share/cassandra/lib/guava-16.0.jar:/usr/share/cassandra/lib/high-scale-lib-1.0.6.jar:/usr/share/cassandra/lib/jackson-core-asl-1.9.2.jar:/usr/share/cassandra/lib/jackson-mapper-asl-1.9.2.jar:/usr/share/cassandra/lib/jamm-0.3.0.jar:/usr/share/cassandra/lib/javax.inject.jar:/usr/share/cassandra/lib/jbcrypt-0.3m.jar:/usr/share/cassandra/lib/jline-1.0.jar:/usr/share/cassandra/lib/jna-4.0.0.jar:/usr/share/cassandra/lib/json-simple-1.1.jar:/usr/share/cassandra/lib/libthrift-0.9.2.jar:/usr/share/cassandra/lib/logback-classic-1.1.2.jar:/usr/share/cassandra/lib/logback-core-1.1.2.jar:/usr/share/cassandra/lib/lz4-1.2.0.jar:/usr/share/cassandra/lib/metrics-core-2.2.0.jar:/usr/share/cassandra/lib/netty-all-4.0.23.Final.jar:/usr/share/cassandra/lib/reporter-config-2.1.0.jar:/usr/share/cassandra/lib/slf4j-api-1.7.2.jar:/usr/share/cassandra/lib/snakeyaml-1.11.jar:/usr/share/cassandra/lib/snappy-java-1.0.5.2.jar:/usr/share/cassandra/lib/stream-2.5.2.jar:/usr/share/cassandra/lib/super-csv-2.1.0.jar:/usr/share/cassandra/lib/thrift-server-0.3.7.jar:/usr/share/cassandra/apache-cassandra-2.1.15.jar:/usr/share/cassandra/apache-cassandra-thrift-2.1.15.jar:/usr/share/cassandra/apache-cassandra.jar:/usr/share/cassandra/cassandra-driver-core-2.0.9.2.jar:/usr/share/cassandra/netty-3.9.0.Final.jar:/usr/share/cassandra/stress.jar: -XX:HeapDumpPath=/var/lib/cassandra/java_1485783495.hprof -XX:ErrorFile=/var/lib/cassandra/hs_err_1485783495.log org.apache.cassandra.service.CassandraDaemon
clearwa+ 18407  0.0  0.0  10472  2132 pts/0    S+   13:38   0:00 grep --color=auto java
clearwater@prov-homestead-1:~$
```

cassandra.pid has the PID of the one that's been more recently started:

```
clearwater@prov-homestead-1:~$ cat /var/run/cassandra/cassandra.pid ; echo ""
20992
clearwater@prov-homestead-1:~$ ls -l /var/run/cassandra/cassandra.pid
-rw-r--r-- 1 cassandra cassandra 5 Jan 30 13:39 /var/run/cassandra/cassandra.pid
```

Neither Cassandra process is listening on port 9160:

```
clearwater@prov-homestead-1:~$ sudo cw-run-in-signaling-namespace netstat -tnlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8888          0.0.0.0:*               LISTEN      25758/homestead
tcp        0      0 10.225.166.181:8888     0.0.0.0:*               LISTEN      25758/homestead
tcp        0      0 0.0.0.0:5658            0.0.0.0:*               LISTEN      25758/homestead
tcp        0      0 0.0.0.0:3868            0.0.0.0:*               LISTEN      25758/homestead
tcp6       0      0 127.0.0.1:55189         :::*                    LISTEN      8990/java
tcp6       0      0 10.225.166.181:7000     :::*                    LISTEN      8990/java
tcp6       0      0 :::5658                 :::*                    LISTEN      25758/homestead
tcp6       0      0 :::3868                 :::*                    LISTEN      25758/homestead
tcp6       0      0 127.0.0.1:7199          :::*                    LISTEN      8990/java
```

monit.log shows it lost track of it at 09:07:35:

```
Reinitializing Monit - Control file '/etc/monit/monitrc'
[UTC Jan 30 09:05:04] info     : 'node-prov-homestead-1.prov.clearwater.test' Monit reloaded
[UTC Jan 30 09:05:04] error    : 'clearwater-craft_process' process is not running
[UTC Jan 30 09:05:04] info     : 'clearwater-craft_process' trying to restart
[UTC Jan 30 09:05:04] info     : 'clearwater-craft_process' restart: /etc/monit/run_logged
[UTC Jan 30 09:05:05] info     : Awakened by the SIGHUP signal
Reinitializing Monit - Control file '/etc/monit/monitrc'
[UTC Jan 30 09:05:06] info     : 'node-prov-homestead-1.prov.clearwater.test' Monit reloaded
[UTC Jan 30 09:05:16] error    : 'clearwater-craft_process' process is not running
[UTC Jan 30 09:05:16] info     : 'clearwater-craft_process' trying to restart
[UTC Jan 30 09:05:16] info     : 'clearwater-craft_process' restart: /etc/monit/run_logged
[UTC Jan 30 09:05:26] info     : 'clearwater-craft_process' process is running with pid 15946
[UTC Jan 30 09:06:59] info     : Monit daemon with pid [1732] stopped
[UTC Jan 30 09:06:59] info     : 'node-prov-homestead-1.prov.clearwater.test' Monit 5.18.1 stopped
[UTC Jan 30 09:07:32] info     : Starting Monit 5.18.1 daemon with http interface at [localhost]:2812
[UTC Jan 30 09:07:32] info     : 'node-prov-homestead-1.prov.clearwater.test' Monit 5.18.1 started
[UTC Jan 30 09:07:32] error    : 'nginx_process' process is not running
[UTC Jan 30 09:07:32] info     : 'nginx_process' trying to restart
[UTC Jan 30 09:07:32] info     : 'nginx_process' restart: /bin/bash
[UTC Jan 30 09:07:34] error    : 'clearwater_cluster_manager_process' process is not running
[UTC Jan 30 09:07:34] info     : 'clearwater_cluster_manager_process' trying to restart
[UTC Jan 30 09:07:34] info     : 'clearwater_cluster_manager_process' restart: /bin/bash
[UTC Jan 30 09:07:35] info     : Awakened by the SIGHUP signal
Reinitializing Monit - Control file '/etc/monit/monitrc'
[UTC Jan 30 09:07:35] info     : 'node-prov-homestead-1.prov.clearwater.test' Monit reloaded
[UTC Jan 30 09:07:35] error    : 'cassandra_process' process is not running
[UTC Jan 30 09:07:35] info     : 'cassandra_process' trying to restart
[UTC Jan 30 09:07:35] info     : 'cassandra_process' restart: /bin/bash
[UTC Jan 30 09:07:38] info     : Awakened by the SIGHUP signal
Reinitializing Monit - Control file '/etc/monit/monitrc'
[UTC Jan 30 09:07:38] info     : 'node-prov-homestead-1.prov.clearwater.test' Monit reloaded
[UTC Jan 30 09:07:40] info     : Awakened by the SIGHUP signal
Reinitializing Monit - Control file '/etc/monit/monitrc'
[UTC Jan 30 09:07:40] info     : 'node-prov-homestead-1.prov.clearwater.test' Monit reloaded
[UTC Jan 30 09:07:41] info     : Awakened by the SIGHUP signal
Reinitializing Monit - Control file '/etc/monit/monitrc'
[UTC Jan 30 09:07:41] info     : 'node-prov-homestead-1.prov.clearwater.test' Monit reloaded
[UTC Jan 30 09:07:52] info     : Awakened by the SIGHUP signal
Reinitializing Monit - Control file '/etc/monit/monitrc'
[UTC Jan 30 09:07:52] info     : 'node-prov-homestead-1.prov.clearwater.test' Monit reloaded
[UTC Jan 30 09:08:11] info     : Awakened by the SIGHUP signal
Reinitializing Monit - Control file '/etc/monit/monitrc'
[UTC Jan 30 09:08:12] info     : 'node-prov-homestead-1.prov.clearwater.test' Monit reloaded
[UTC Jan 30 09:08:12] error    : 'cassandra_process' process is not running
[UTC Jan 30 09:08:12] info     : 'cassandra_process' trying to restart
[UTC Jan 30 09:08:12] info     : 'cassandra_process' restart: /bin/bash
[UTC Jan 30 09:08:13] info     : Awakened by the SIGHUP signal
Reinitializing Monit - Control file '/etc/monit/monitrc'
```

However, homestead-prov didn't fail until 9:50:02:

```
30-01-2017 09:50:02.505 UTC ERROR base.py:363: Exception: TTransportException('Connection closed',)
```

I applied a patch at 09:06:56, so this probably triggered it (maybe the frequent reloading of monit meant it lost track of the process?). From that point, I think there would have been a second Cassandra process starting, failing to bind to the right port, and exiting again (relatively harmlessly).

However, eventually the two Cassandra processes trod on each others' toes, causing the first process to shut down port 9160 but not exit, and this is when failures started:

```
INFO  [MemtableFlushWriter:291] 2017-01-30 09:50:00,165 Memtable.java:382 - Completed flushing /var/lib/cassandra/data/homestead_provisioning/public-b6cba080def911e68581919dd30b2542/homestead_provisioning-public-tmp-ka-2-Data.db (2.272MiB) for commitlog position ReplayPosition(segmentId=1485273701570, position=28660641)
ERROR [COMMIT-LOG-ALLOCATOR] 2017-01-30 09:50:00,206 StorageService.java:453 - Stopping gossiper
WARN  [COMMIT-LOG-ALLOCATOR] 2017-01-30 09:50:00,206 StorageService.java:359 - Stopping gossip by operator request
INFO  [COMMIT-LOG-ALLOCATOR] 2017-01-30 09:50:00,206 Gossiper.java:1454 - Announcing shutdown
INFO  [COMMIT-LOG-ALLOCATOR] 2017-01-30 09:50:00,208 StorageService.java:1715 - Node /10.225.166.181 state jump to shutdown
ERROR [COMMIT-LOG-ALLOCATOR] 2017-01-30 09:50:02,290 StorageService.java:458 - Stopping RPC server
INFO  [COMMIT-LOG-ALLOCATOR] 2017-01-30 09:50:02,291 ThriftServer.java:142 - Stop listening to thrift clients
ERROR [COMMIT-LOG-ALLOCATOR] 2017-01-30 09:50:02,297 StorageService.java:463 - Stopping native transport
INFO  [COMMIT-LOG-ALLOCATOR] 2017-01-30 09:50:02,390 Server.java:225 - Stop listening for CQL clients
ERROR [COMMIT-LOG-ALLOCATOR] 2017-01-30 09:50:02,390 CommitLog.java:398 - Failed managing commit log segments. Commit disk failure policy is stop; terminating thread
java.lang.AssertionError: attempted to delete non-existing file CommitLog-4-1485273701551.log
        at org.apache.cassandra.io.util.FileUtils.deleteWithConfirm(FileUtils.java:125) ~[apache-cassandra-2.1.15.jar:2.1.15]
        at org.apache.cassandra.db.commitlog.CommitLogSegment.delete(CommitLogSegment.java:343) ~[apache-cassandra-2.1.15.jar:2.1.15]
        at org.apache.cassandra.db.commitlog.CommitLogSegmentManager$5.call(CommitLogSegmentManager.java:424) ~[apache-cassandra-2.1.15.jar:2.1.15]
        at org.apache.cassandra.db.commitlog.CommitLogSegmentManager$5.call(CommitLogSegmentManager.java:419) ~[apache-cassandra-2.1.15.jar:2.1.15]
        at org.apache.cassandra.db.commitlog.CommitLogSegmentManager$1.runMayThrow(CommitLogSegmentManager.java:153) ~[apache-cassandra-2.1.15.jar:2.1.15]
        at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) [apache-cassandra-2.1.15.jar:2.1.15]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
```

#### Impact

Failure of a Cassandra process, causing reduced redundancy. We would never recover from this state.

#### Release and environment 

10.0.0-170127-~255.00.0-170127.020342. I was on 10.0.0-170106 before  the upgrade.

#### Steps to reproduce

Unknown - I don't think this reproduces reliably. It could probably be partially reproduced by corrupting /var/run/cassandra/cassandra.pid (to get us into a state where Monit had lost track of the process).

Reloading monit repeatedly might reproduce it.

**Comment by rkd-msw** [comment]
I don't think this is a duplicate of https://github.com/Metaswitch/clearwater-cassandra/issues/118 - in this case, Cassandra becoming unresponsive is a follow-on effect of monit losing track of it.

I think the fix for that relies on /var/run/cassandra/cassandra.pid being correct, whereas it won't be here (as soon as monit loses track of Cassandra and tries to start a second one, the PID in that file is wrong).

**Comment by rkd-msw** [comment]
I've fixed this up on my system by manually correcting /var/run/cassandra/cassandra.pid then killing the unresponsive process.

**Comment by johadalin** [comment]
#127 Fixes this issue, by killing any rogue cassandra processes that don't match the PID in the pidfile. This is now in line with our other init scripts.
I'm not exactly sure what caused us to have two processes, but this should kill all but the one in the pidfile, so we should get back to a good state quickly.

Passing back to @rkd-msw : I'm not sure if you can properly re-test, beyond the same live testing i've done: change the number in the pidfile, wait for monit to detect the process 'isn't running', watch as it calls the init file, which will kill the rogue cassandra and start a new one, logging to syslog the old process that is killed. 
Leaving it up to your judgement if that is enough for you to close this issue down.

**Comment by rkd-msw** [comment]
I can't think of any other testing it's worth doing. I've tried (and failed) to reproduce the original scenario by running "sudo reload clearwater-monit" in a loop.
