### ISSUE TITLE
Cassandra sometimes not listening on port 9160

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/clearwater-cassandra#26]
I had a system where cassandra was running, but not listening on port 9160 (the thrift RPC port).

At present the monit config to monitor this port is commented out because it produced false positives. I Suspect these were actually true positives!

Restarting Cassandra fixed the problem. 

The cassandra log showed that an internal thread had crashed the day before, but I'm not sure that this is related:

```
ERROR [CompactionExecutor:2] 2015-03-30 16:53:22,344 CassandraDaemon.java (line 191) Exception in thread Thread[CompactionExecutor:2,1,main]
FSWriteError in /var/lib/cassandra/data/system/peers/system-peers-tmp-ic-39-CompressionInfo.db
        at org.apache.cassandra.io.compress.CompressionMetadata$Writer.writeHeader(CompressionMetadata.java:267)
        at org.apache.cassandra.io.compress.CompressedSequentialWriter.<init>(CompressedSequentialWriter.java:78)
        at org.apache.cassandra.io.compress.CompressedSequentialWriter.open(CompressedSequentialWriter.java:41)
        at org.apache.cassandra.io.sstable.SSTableWriter.<init>(SSTableWriter.java:97)
        at org.apache.cassandra.db.ColumnFamilyStore.createCompactionWriter(ColumnFamilyStore.java:2000)
        at org.apache.cassandra.db.compaction.CompactionTask.runWith(CompactionTask.java:143)
        at org.apache.cassandra.io.util.DiskAwareRunnable.runMayThrow(DiskAwareRunnable.java:48)
        at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28)
        at org.apache.cassandra.db.compaction.CompactionTask.executeInternal(CompactionTask.java:58)
        at org.apache.cassandra.db.compaction.AbstractCompactionTask.execute(AbstractCompactionTask.java:60)
        at org.apache.cassandra.db.compaction.CompactionManager$BackgroundCompactionTask.run(CompactionManager.java:208)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)
Caused by: java.io.IOException: No space left on device
        at java.io.RandomAccessFile.writeBytes(Native Method)
        at java.io.RandomAccessFile.write(RandomAccessFile.java:502)
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:401)
        at java.io.RandomAccessFil INFO [CompactionExecutor:3] 2015-03-30 20:48:14,806 AutoSavingCache.java (line 289) Saved KeyCache (23 items) in 102 ms
```

(note this exception says the node was out of disk space - when I looked it did have enough space).

**Comment by graemerobertson** [comment]
I've seen similar things to this - Cassandra not listening on port 9160, and crashing with complaints about not having enough disk space. We allegedly had 1.1GB of disk available; the commitlog was just under 1GB - perhaps something weird is going on when cassandra loads the commitlog on start up.

**Comment by graemerobertson** [comment]
@bossmc thinks it might be something like this - http://mail-archives.apache.org/mod_mbox/cassandra-user/201405.mbox/%3CCAD_Xd-K7KyCS7ofp5M_RAfC=htqpuQOx=tq6GZsOK_vty5o+GQ@mail.gmail.com%3E

**Comment by kjw1** [comment]
I was able to work around this issue by running

    nodetool enablethrift

without needing to restart cassandra.

**Comment by rkd-msw** [comment]
https://github.com/Metaswitch/clearwater-cassandra/commit/11d117d5986190477106ff9b8ec45d2492ae5b93 re-runs `nodetool enablethrift` on a failure, so this should be fixed.
