### ISSUE TITLE
There appears to be a compatibility issue between version  1.2.12 and 2.0.14 when running the spin up new nodes upgrade procedure

### ISSUE THREAD

**Issue by tcaterisano** [Metaswitch/clearwater-cassandra#44]
There appears to be a compatibility issue between version  1.2.12 and 2.0.14 when running the spin up new nodes upgrade procedure.

https://issues.apache.org/jira/browse/CASSANDRA-8768 which suggests that you can’t do a scale-in/scale-out upgrade in Cassandra (you’re supposed to do an in-place upgrade).  The issue linked is about the 2.0 -> 2.1 upgrade, but looks like the same issue affecting 1.2 -> 2.0.

```
ERROR [main] 2015-06-19 18:29:40,728 CassandraDaemon.java (line 584) Exception encountered during startup
java.lang.RuntimeException: Unable to gossip with any seeds
        at org.apache.cassandra.gms.Gossiper.doShadowRound(Gossiper.java:1234)
        at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:452)
        at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:666)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:618)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:510)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:437)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:567)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:656)
 INFO [StorageServiceShutdownHook] 2015-06-19 18:29:40,733 Gossiper.java
```

**Comment by mirw** [comment]
@bossmc, please can you take a look?

**Comment by bossmc** [comment]
After discussion with Terry and reading the Cassandra docs/code, it has become apparent that Cassandra does not support bootstrapping a node from a down-level node (it's happy to run with mixed versions, but not to make topology changes at the same time).  This implies that Cassandra upgrades must be done "in-place", not as a rolling upgrade.

**Comment by bossmc** [comment]
Closing as there's no issue here.
